name: pmd-deps

services:
  mongo:
    image: mongo:7
    container_name: pmd-mongo
    ports:
      - "27017:27017"
    volumes:
      - pmd_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: pmd-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pmd_mongo_data:
